steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/pro-pooja/$REPO_NAME']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/your-app-image:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/your-app-image:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', '$REPO_NAME', '--image', 'gcr.io/$PROJECT_ID/your-app-image:$SHORT_SHA', '--region', 'europe-west2', '--port', '$PORT']

images:
  - 'gcr.io/$PROJECT_ID/your-app-image'

options:
  logging: CLOUD_LOGGING_ONLY
