steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/pro-pooja/$REPO_NAME']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/your-app-image', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/your-app-image']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'your-app', '--image', 'gcr.io/$PROJECT_ID/your-app-image' '--region', 'europe-west2']

images:
  - 'gcr.io/$PROJECT_ID/your-app-image'

options:
  logging: CLOUD_LOGGING_ONLY
